# Generated by Django 2.2.4 on 2019-08-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='Date article published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
