# Generated by Django 2.2.4 on 2019-08-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190818_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='Date published',
        ),
    ]
