# Generated by Django 2.2.4 on 2019-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190826_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='Date published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date article published'),
        ),
    ]
