# Generated by Django 2.2.4 on 2019-09-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190826_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='image',
            new_name='post_image',
        ),
    ]
